# TIPODE DATO
print("Escribe tu Nombre: ")
nombredepersona = str(input())
print("Escribe tu edad: ")
edaddepersona = input()
print("Escribe tu Altura: ")
altura = str(input())
print("Eres soltero: ")
Soltero = str(input())
# nombredepersona = 13
print("Nombre: " +nombredepersona)
print("Edad: " + str(edaddepersona))
print("Altura: " + str(altura))
print("Soltero: " + str(Soltero))
print(type(nombredepersona))
print(type(edaddepersona))
print(type(altura))
print(type(Soltero))